name: Deploy Worker Production

on:
  push:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - name: Deploy Production
        uses: cloudflare/wrangler-action@v3
        with:
          # Variables dépréciées, il faut utiliser `CLOUDFLARE_`
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'apps/worker'
          packageManager: pnpm
          wranglerVersion: '4.116.0'
          environment: production
